"""create phase 2 domain schema

Revision ID: f60a72e9a0ac
Revises: 
Create Date: 2026-09-02 22:18:40.869005
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f60a72e9a0ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('scheme', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classifications')),
    sa.UniqueConstraint('scheme', 'code', name='uq_classifications_scheme_code')
    )
    op.create_table('ingestion_runs',
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records_discovered', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_source_name'), 'ingestion_runs', ['source_name'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('external_identifier', sa.String(length=255), nullable=False),
    sa.Column('source_status', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_source_records_ingestion_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('source_type', 'external_identifier', name='uq_source_records_type_identifier')
    )
    op.create_index(op.f('ix_source_records_ingestion_run_id'), 'source_records', ['ingestion_run_id'], unique=False)
    op.create_index('ix_source_records_type_identifier', 'source_records', ['source_type', 'external_identifier'], unique=False)
    op.create_table('certifications',
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('external_identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_certifications_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications')),
    sa.UniqueConstraint('scheme_name', 'external_identifier', name='uq_certifications_scheme_external')
    )
    op.create_index(op.f('ix_certifications_source_record_id'), 'certifications', ['source_record_id'], unique=False)
    op.create_table('crs_records',
    sa.Column('registration_number', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_crs_records_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crs_records')),
    sa.UniqueConstraint('registration_number', name='uq_crs_records_registration')
    )
    op.create_index(op.f('ix_crs_records_source_record_id'), 'crs_records', ['source_record_id'], unique=False)
    op.create_table('hallmarking_rules',
    sa.Column('rule_identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_hallmarking_rules_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hallmarking_rules')),
    sa.UniqueConstraint('rule_identifier', name=op.f('uq_hallmarking_rules_rule_identifier'))
    )
    op.create_index('ix_hallmarking_rules_material', 'hallmarking_rules', ['material'], unique=False)
    op.create_index(op.f('ix_hallmarking_rules_source_record_id'), 'hallmarking_rules', ['source_record_id'], unique=False)
    op.create_table('qco_records',
    sa.Column('notification_number', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_qco_records_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qco_records')),
    sa.UniqueConstraint('notification_number', name='uq_qco_records_notification')
    )
    op.create_index(op.f('ix_qco_records_source_record_id'), 'qco_records', ['source_record_id'], unique=False)
    op.create_table('standards',
    sa.Column('is_number', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('standard_type', sa.String(length=80), nullable=True),
    sa.Column('publication_info', sa.Text(), nullable=True),
    sa.Column('review_info', sa.Text(), nullable=True),
    sa.Column('technical_committee', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('superseding_standard_id', sa.String(length=36), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_standards_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseding_standard_id'], ['standards.id'], name=op.f('fk_standards_superseding_standard_id_standards'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standards')),
    sa.UniqueConstraint('is_number', name=op.f('uq_standards_is_number'))
    )
    op.create_index(op.f('ix_standards_source_record_id'), 'standards', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_standards_status'), 'standards', ['status'], unique=False)
    op.create_index('ix_standards_title', 'standards', ['title'], unique=False)
    op.create_table('crs_mappings',
    sa.Column('crs_record_id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crs_record_id'], ['crs_records.id'], name=op.f('fk_crs_mappings_crs_record_id_crs_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_crs_mappings_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crs_mappings')),
    sa.UniqueConstraint('crs_record_id', 'standard_id', name='uq_crs_mappings_record_standard')
    )
    op.create_index(op.f('ix_crs_mappings_crs_record_id'), 'crs_mappings', ['crs_record_id'], unique=False)
    op.create_index(op.f('ix_crs_mappings_standard_id'), 'crs_mappings', ['standard_id'], unique=False)
    op.create_table('qco_mappings',
    sa.Column('qco_record_id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('applicability_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['qco_record_id'], ['qco_records.id'], name=op.f('fk_qco_mappings_qco_record_id_qco_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_qco_mappings_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qco_mappings')),
    sa.UniqueConstraint('qco_record_id', 'standard_id', name='uq_qco_mappings_record_standard')
    )
    op.create_index(op.f('ix_qco_mappings_qco_record_id'), 'qco_mappings', ['qco_record_id'], unique=False)
    op.create_index(op.f('ix_qco_mappings_standard_id'), 'qco_mappings', ['standard_id'], unique=False)
    op.create_table('standard_classifications',
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('classification_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], name=op.f('fk_standard_classifications_classification_id_classifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_standard_classifications_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('standard_id', 'classification_id', name=op.f('pk_standard_classifications')),
    sa.UniqueConstraint('standard_id', 'classification_id', name='uq_standard_classifications_pair')
    )
    op.create_table('standard_relationships',
    sa.Column('source_standard_id', sa.String(length=36), nullable=False),
    sa.Column('target_standard_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_standard_id <> target_standard_id', name=op.f('ck_standard_relationships_no_self_reference')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_standard_relationships_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_standard_id'], ['standards.id'], name=op.f('fk_standard_relationships_source_standard_id_standards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_standard_id'], ['standards.id'], name=op.f('fk_standard_relationships_target_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_relationships')),
    sa.UniqueConstraint('source_standard_id', 'target_standard_id', 'relationship_type', name='uq_standard_relationships_pair_type')
    )
    op.create_index(op.f('ix_standard_relationships_source_record_id'), 'standard_relationships', ['source_record_id'], unique=False)
    op.create_index('ix_standard_relationships_target_type', 'standard_relationships', ['target_standard_id', 'relationship_type'], unique=False)
    op.create_table('standard_versions',
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('edition_label', sa.String(length=100), nullable=False),
    sa.Column('edition_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_standard_versions_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_standard_versions_standard_id_standards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_versions')),
    sa.UniqueConstraint('standard_id', 'edition_year', name='uq_standard_versions_standard_year')
    )
    op.create_index(op.f('ix_standard_versions_source_record_id'), 'standard_versions', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_standard_versions_standard_id'), 'standard_versions', ['standard_id'], unique=False)
    op.create_index('ix_standard_versions_year', 'standard_versions', ['edition_year'], unique=False)
    op.create_table('amendments',
    sa.Column('standard_version_id', sa.String(length=36), nullable=False),
    sa.Column('amendment_label', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_amendments_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], name=op.f('fk_amendments_standard_version_id_standard_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amendments')),
    sa.UniqueConstraint('standard_version_id', 'amendment_label', name='uq_amendments_version_label')
    )
    op.create_index(op.f('ix_amendments_source_record_id'), 'amendments', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_amendments_standard_version_id'), 'amendments', ['standard_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amendments_standard_version_id'), table_name='amendments')
    op.drop_index(op.f('ix_amendments_source_record_id'), table_name='amendments')
    op.drop_table('amendments')
    op.drop_index('ix_standard_versions_year', table_name='standard_versions')
    op.drop_index(op.f('ix_standard_versions_standard_id'), table_name='standard_versions')
    op.drop_index(op.f('ix_standard_versions_source_record_id'), table_name='standard_versions')
    op.drop_table('standard_versions')
    op.drop_index('ix_standard_relationships_target_type', table_name='standard_relationships')
    op.drop_index(op.f('ix_standard_relationships_source_record_id'), table_name='standard_relationships')
    op.drop_table('standard_relationships')
    op.drop_table('standard_classifications')
    op.drop_index(op.f('ix_qco_mappings_standard_id'), table_name='qco_mappings')
    op.drop_index(op.f('ix_qco_mappings_qco_record_id'), table_name='qco_mappings')
    op.drop_table('qco_mappings')
    op.drop_index(op.f('ix_crs_mappings_standard_id'), table_name='crs_mappings')
    op.drop_index(op.f('ix_crs_mappings_crs_record_id'), table_name='crs_mappings')
    op.drop_table('crs_mappings')
    op.drop_index('ix_standards_title', table_name='standards')
    op.drop_index(op.f('ix_standards_status'), table_name='standards')
    op.drop_index(op.f('ix_standards_source_record_id'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_qco_records_source_record_id'), table_name='qco_records')
    op.drop_table('qco_records')
    op.drop_index(op.f('ix_hallmarking_rules_source_record_id'), table_name='hallmarking_rules')
    op.drop_index('ix_hallmarking_rules_material', table_name='hallmarking_rules')
    op.drop_table('hallmarking_rules')
    op.drop_index(op.f('ix_crs_records_source_record_id'), table_name='crs_records')
    op.drop_table('crs_records')
    op.drop_index(op.f('ix_certifications_source_record_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_source_records_type_identifier', table_name='source_records')
    op.drop_index(op.f('ix_source_records_ingestion_run_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source_name'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('classifications')
    # ### end Alembic commands ###